# Generated by Django 5.1 on 2024-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('last_run_timestamp', models.DateTimeField(blank=True, null=True)),
                ('next_run_timestamp', models.DateTimeField(blank=True, null=True)),
                ('schedule_interval', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
